name: Build GitHub Pages
on:
  push:
    branches:
      - vanilla
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: vanilla
      - name: Publish
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          build_dir: .
          target_branch: vanilla
