name: Build GitHub Pages
on:
  push:
    branches:
      - vanilla
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: vanilla
      - name: Build
        run: echo "skipped"
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: "Content"
          path: ./
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v2
        with:
          name: "Content"
          path: .
      - name: Publish
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          build_dir: .
          target_branch: vanilla-publish
          jekyll: false
